[build]
  publish = "."
  command = "none"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/about/"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/products/"
  to = "/products.html"
  status = 200

[[redirects]]
  from = "/technology/"
  to = "/technology.html"
  status = 200

[[redirects]]
  from = "/contact/"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "http://aepower-website.netlify.app/*"
  to = "https://aepower-website.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "www.aepower-website.netlify.app/*"
  to = "https://aepower-website.netlify.app/:splat"
  status = 301
  force = true
